### ISSUE TITLE
Diagrama DER

### ISSUE THREAD

**Issue by juanmroude** [classroomEntreRios/proyecto-g1d-proyecto-g1d#1]
Realizar Diagrama DER

**Comment by seroselli** [comment]
![dfs_der1_v2](https://user-images.githubusercontent.com/53358704/106814766-a9145c00-6651-11eb-8beb-3f9f625f7ebf.png)

**Comment by seroselli** [comment]
![der](https://user-images.githubusercontent.com/53358704/109577350-340f3780-7ad4-11eb-84c9-3b4307740a04.jpg)
Adjunto último Diagrama entidad-relacion
