### ISSUE TITLE
Diagrama de Clases

### ISSUE THREAD

**Issue by seroselli** [classroomEntreRios/proyecto-g1d-proyecto-g1d#2]

**Comment by juanmroude** [comment]
![Diagrama de clases](https://user-images.githubusercontent.com/71778852/108285056-169dad80-7165-11eb-9bae-1536a7b6b6a5.png)

**Comment by juanmroude** [comment]
![Diagrama de clases final](https://user-images.githubusercontent.com/71778852/108429656-0a762680-721f-11eb-91fc-29b664104953.png)

**Comment by seroselli** [comment]
Finalizado
