### ISSUE TITLE
Modelo Relacional

### ISSUE THREAD

**Issue by juanmroude** [classroomEntreRios/proyecto-g1d-proyecto-g1d#4]
Modelo Relacional

**Comment by fsatopna** [comment]
Modelo Relacional Inicial

**Comment by fsatopna** [comment]
Modelo relacional inicial

**Comment by seroselli** [comment]
![dfs_der1_v2](https://user-images.githubusercontent.com/53358704/107579111-69122380-6bd3-11eb-9f06-9467135e080b.png)
Modelo relacional inicial

**Comment by fsatopna** [comment]
[normalizacion_Viajar_esquema0.docx](https://github.com/classroomEntreRios/proyecto-g1d-proyecto-g1d/files/5961844/normalizacion_Viajar_esquema0.docx)

Modelo Relacional

**Comment by juanmroude** [comment]
[Modelo relacional.pdf](https://github.com/classroomEntreRios/proyecto-g1d-proyecto-g1d/files/6006387/Modelo.relacional.pdf)

**Comment by seroselli** [comment]
![Modelo relacional](https://user-images.githubusercontent.com/53358704/109577765-ee06a380-7ad4-11eb-8c2b-014a0c09e95c.jpg)
